version: "3.9"

services:
    flask_app:
      container_name: flask_app
      build: .
      ports:
          - "5000:5000"
      environment:
        - DATABASE_URL=postgresql://postgres:postgres@flask_db:5432/postgres
      depends_on:
        - flask_db
    flask_db:
      image: postgres:latest
      ports:
        - "5432:5432"
      container_name: flask_db
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=postgres
      volumes:
        - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}